#!/usr/bin/env python3
"""Regenerate models/tbi-wiring-todo.json: which paper connections are
represented in models/tbi.json and which still need wiring.

For agents extending the model: work down the entries with wired=false.
Matching is fuzzy (label ↔ node name similarity) and same-graph reference
checks are textual, so treat flags as strong hints, not ground truth —
`pnpm sim models/tbi.json` after every change.

Usage: python3 scripts/tbi_coverage.py
"""
import difflib
import json
import re

MODEL = json.load(open("models/tbi.json"))
PAPER = json.load(open("models/tbi-paper-map.json"))

ARTIFACTS = {"background", "background2", "rows", "navigation guide", "impact"}

# All model nodes with their graph + searchable text
nodes = []
for gid, g in MODEL["graphs"].items():
    for n in g["nodes"]:
        if n["type"] in ("note",):
            continue
        nodes.append({
            "graph": gid, "id": n["id"],
            "name": (n.get("name") or n["id"]).lower(),
            "formula": n.get("formula", "") + " " + n.get("initial", ""),
        })

def normalize(s):
    s = s.lower().replace("&", "and").replace("/", " ").replace("-", " ")
    return re.sub(r"\s+", " ", s).strip()

def best_node(label):
    lab = normalize(label)
    scored = []
    for n in nodes:
        score = difflib.SequenceMatcher(None, lab, normalize(n["name"])).ratio()
        # token overlap bonus for long labels
        lt, nt = set(lab.split()), set(normalize(n["name"]).split())
        if lt and nt:
            score += 0.35 * len(lt & nt) / max(len(lt), 1)
        scored.append((score, n))
    scored.sort(key=lambda x: -x[0])
    top = scored[0]
    return top[1] if top[0] > 0.62 else None

coverage, missing = {}, []
for el in PAPER["elements"]:
    label = el["label"]
    if normalize(label) in ARTIFACTS:
        continue
    m = best_node(label)
    if m:
        coverage[label] = f"{m['graph']}:{m['id']}"
    else:
        missing.append(label)

# connection wiring check (same-graph textual; cross-graph flagged for review)
by_key = {v: k for k, v in coverage.items()}
node_ix = {(n["graph"], n["id"]): n for n in nodes}
todo, wired = [], 0
for c in PAPER["connections"]:
    f, t = coverage.get(c["from"]), coverage.get(c["to"])
    entry = {"from": c["from"], "to": c["to"], "polarity": c["polarity"], "source": c["source"]}
    if not f or not t:
        entry["status"] = "endpoint-missing"
        entry["mapped"] = {"from": f, "to": t}
        todo.append(entry)
        continue
    fg, fid = f.split(":")
    tg, tid = t.split(":")
    if fg == tg:
        target = node_ix[(tg, tid)]
        if re.search(rf"\b{re.escape(fid)}\b", target["formula"]):
            wired += 1
            continue
        # also accept references via the goal-seeking adj flow
        adj = node_ix.get((tg, f"{tid}_adj"))
        if adj and re.search(rf"\b{re.escape(fid)}\b", adj["formula"]):
            wired += 1
            continue
        entry["status"] = "unwired"
    else:
        entry["status"] = "cross-module-verify"
    entry["mapped"] = {"from": f, "to": t}
    todo.append(entry)

out = {
    "note": "Generated by scripts/tbi_coverage.py — regenerate after editing models/tbi.json. Entries with status 'unwired' are same-graph paper connections with no matching formula reference; 'cross-module-verify' cross graphs (check main wiring); 'endpoint-missing' lack a mapped node entirely.",
    "stats": {
        "paper_elements": len(coverage) + len(missing),
        "covered": len(coverage),
        "unmapped_elements": missing,
        "connections": len(PAPER["connections"]),
        "wired_same_graph": wired,
        "todo": len(todo),
    },
    "coverage": dict(sorted(coverage.items())),
    "todo": todo,
}
json.dump(out, open("models/tbi-wiring-todo.json", "w"), indent=1, ensure_ascii=False)
s = out["stats"]
print(f"elements covered: {s['covered']}/{s['paper_elements']} (unmapped: {len(s['unmapped_elements'])})")
print(f"connections: {s['wired_same_graph']} wired same-graph, {s['todo']} to review")
for m in s["unmapped_elements"]:
    print("  missing:", m)
